version: "3"
services:
  node1:
    build: .
    container_name: node1
    ports:
      - "5001:5000"
    environment:
      - NODE_ID=0
      - PEER_URLS=http://node2:5000,http://node3:5000
    networks:
      - kv-net

  node2:
    build: .
    container_name: node2
    ports:
      - "5002:5000"
    environment:
      - NODE_ID=1
      - PEER_URLS=http://node1:5000,http://node3:5000
    networks:
      - kv-net

  node3:
    build: .
    container_name: node3
    ports:
      - "5003:5000"
    environment:
      - NODE_ID=2
      - PEER_URLS=http://node1:5000,http://node2:5000
    networks:
      - kv-net

networks:
  kv-net:
